apiVersion: v1
kind: ServiceAccount
metadata:
  name: nlp-readonly
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nlp-readonly
rules:
  - apiGroups: [""]
    resources: ["pods","services","configmaps","persistentvolumeclaims"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nlp-readonly-binding
subjects:
  - kind: ServiceAccount
    name: nlp-readonly
    namespace: default
roleRef:
  kind: ClusterRole
  name: nlp-readonly
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nlp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-nlp-service
  template:
    metadata:
      labels:
        app: k8s-nlp-service
    spec:
      serviceAccountName: nlp-readonly
      containers:
        - name: backend
          image: minnuantony/k8s-nlp-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-bedrock-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-bedrock-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-bedrock-secret
                  key: AWS_REGION
            - name: BEDROCK_MODEL
              valueFrom:
                secretKeyRef:
                  name: aws-bedrock-secret
                  key: BEDROCK_MODEL

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-nlp-service
spec:
  selector:
    app: k8s-nlp-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
